eureka:
  server:
    enable-self-preservation: false
    evictionIntervalTimerInMs: 3000  
  client:
    register-with-eureka: false 
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka

spring:
  profiles:
      active: test
      
user:
   age: 36
