spring:
  security:
         user:
           roles: user
           name: admin
           password: admin
           
server:
    port: 9001
     
eureka:
  instance:
    hostname: eurekaserver
              
user:
   age: 36
