spring:
  security:
         user:
           roles: user
           name: admin
           password: admin
           
server:
    port: 9001
    context-path: test
     
eureka:
  instance:
    hostname: eureka-server1
              
user:
   age: 36
