server:
  port: 9001

eureka:
  instance:
    hostname: eureka-server1
  client:
    registerWithEureka: false #表示是否注册自身到eureka服务器， 做集群是设置成true 生产配置为true
    fetchRegistry: false #表示是否从eureka服务器获得注册信息，生产配置为true
    registry-fetch-interval-seconds: 5 #默认为30s 生产使用缺省时间，测试环境修改小点
    lease-renewal-interval-in-seconds: 5 #心跳时间，生产使用缺省时间，即服务续约间隔时间（缺省为30秒，生产使用缺省时间，测试环境修改小点）
    lease-expiration-duration-in-seconds: 10 #发呆时间，即服务续约到期时间（缺省为90秒，生产使用缺省时间，测试环境修改小点）
    serviceUrl:
      defaultZone: http://admin:admin@eureka-server1:9001/eureka
  server:
    enableSelfPreservation: false #关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000 #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms），测试环境修改小点spring.security.user.roles=USER
spring:
  security:
       user:
         roles: USER
         name: admin
         password: admin
