eureka:
  server:
    enable-self-preservation: false
    evictionIntervalTimerInMs: 3000  
  client:
    registerWithEureka: false 
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: eureka-server1
    preferIpAddress: true
spring:
  application:
    name: eureka-server1
  security:
    user:
      roles: user
      name: admin
      password: admin
      
server:
    port: 9001
          
user:
   age: 36

